source 'https://github.com/CocoaPods/Specs.git'


target 'LiveEB_Demo' do
 platform :ios, '9.0'
 
 pod 'TWebRTC', :git=>'https://github.com/tencentyun/TWebRTC-IOS-SDK.git' , :tag => '1.6.3'

 pod 'LiveEB_IOS', :git=>'https://github.com/tencentyun/LEBSDK_IOS.git' , :tag => '1.0.0'
  
end
